[templates."Xiaomi 17 Pro Max"]
manufacturer = "Xiaomi"
brand = "Xiaomi"
model = "2509FPN0BC"
device = "popsicle"
product = "popsicle"
fingerprint = ""
name = "popsicle"
marketname = "Xiaomi 17 Pro Max"
